//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovasubBSL430 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InnovasubBSL430.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @2500
        ///00 07 07 37 31 40 90 33 B0 13 94 2F 0C 93 00 24
        ///B0 13 10 2F FF 3F 12 01 00 02 00 00 00 08 47 20
        ///00 02 09 01 00 00 00 01 06 00 FF 09 01 A1 01 85
        ///3F 95 3F 75 08 25 01 15 01 09 01 81 02 85 3F 95
        ///3F 75 08 25 01 15 01 09 01 91 02 C0 09 02 29 00
        ///01 01 00 80 32 09 04 00 00 02 03 00 00 00 09 21
        ///01 01 00 01 22 24 00 07 05 81 03 40 00 01 07 05
        ///01 03 40 00 01 FF F2 B0 0F 00 84 23 09 20 C2 93
        ///84 23 03 34 5E 42 20 09 0B 3C 5E 42 22 09 08 3C
        ///C2 93 84 23 03 34 5E 42 C8 23 02 3C 5E 42 88 23
        ///7E F2 C2 4E EA  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RAM_BSL00078838 {
            get {
                return ResourceManager.GetString("RAM_BSL00078838", resourceCulture);
            }
        }
    }
}
